name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4 # Check https://pages.github.com/versions/ for the current Ruby version used by gh pages.

      # Install dependencies
      - name: Install dependencies
        run: |
          # Update gem and bundler - disabled due to gem install errors on CI
          # gem update --system --no-document
          gem update bundler --no-document
          # Set the bundle directory
          bundle config set path vendor/bundle
          # Install Gemfile contents via bundler
          bundle install

      # Build the website
      - name: run jekyll
        run: bundle exec jekyll build --drafts